version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: trip-builder-app
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./trip-builder:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: trip-builder-webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./trip-builder:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: trip-builder-db
    tty: true
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: trip_builder
      MYSQL_USER: trip-builder-web
      MYSQL_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
